# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [2]:
# Import libraries
import numpy as np
import pandas as pd

In [12]:
# Importing the dataset from data folder or link provided in challenge 1

pokemon = pd.read_csv('data/pokemon_updated.csv')
pokemon.head()

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [14]:
# your code here

pokemon.head()

pokemon['check total'] = (pokemon['Total'] == pokemon['HP'] + pokemon['Attack'] + pokemon['Defense'] + pokemon['Sp. Atk'] + pokemon['Sp. Def'] + pokemon['Speed'])

pokemon.groupby(['check total']).mean()

,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
check total,,,,,,,,,
True,435.1025,69.25875,79.00125,73.8425,72.82,71.9025,68.2775,3.32375,0.08125

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](images/one-hot-encoding.png)

In [15]:
# your code here

one_hot_type1 = pd.get_dummies(pokemon['Type 1'])
one_hot_type2 = pd.get_dummies(pokemon['Type 2'])

one_hot_type1.head()

,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

In [16]:
one_hot_type2.head()

,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [17]:
one_hottypes = one_hot_type1 + one_hot_type2

one_hottypes.head()

,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [18]:
# your code here

pokemon_onehot = pd.concat([pokemon, one_hottypes], axis = 1)
pokemon_onehot.head()

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,check total,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,True,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,True,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,True,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,True,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,True,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

In [19]:
pokemon_onehot_corr = pokemon_onehot.corr()
pokemon_onehot_corr

,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,check total,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
Total,1.000000,0.618748,0.736211,0.612787,0.747250,0.717609,0.575943,0.048384,0.501758,NaN,-0.145781,0.056154,0.229705,0.020971,-0.036698,0.077786,0.078726,0.059383,0.003641,-0.052592,0.015060,0.060248,-0.105331,-0.090441,0.124688,0.032731,0.109703,-0.021665
HP,0.618748,1.000000,0.422386,0.239622,0.362380,0.378718,0.175952,0.058683,0.273620,NaN,-0.154326,0.009986,0.138023,-0.061303,-0.007046,0.055398,0.010371,0.031394,-0.062262,-0.046120,0.074916,0.082021,0.111999,-0.075668,0.027239,-0.035514,-0.043037,0.029906
Attack,0.736211,0.422386,1.000000,0.438687,0.396362,0.263990,0.381240,0.051451,0.345408,NaN,-0.070168,0.143057,0.212999,-0.075471,-0.123250,0.210706,0.046438,0.014373,-0.015735,-0.062674,0.127416,0.021007,-0.074769,-0.073370,-0.069773,0.101043,0.107505,-0.070578
Defense,0.612787,0.239622,0.438687,1.000000,0.223549,0.510747,0.015227,0.042419,0.246377,NaN,-0.027563,-0.024293,0.105864,-0.060502,-0.025342,0.001830,-0.035472,-0.068486,0.060864,-0.006948,0.134451,0.020174,-0.174609,-0.093942,0.010685,0.298242,0.350559,0.006259
Sp. Atk,0.747250,0.362380,0.396362,0.223549,1.000000,0.506121,0.473018,0.036437,0.448907,NaN,-0.185128,0.036953,0.194388,0.127434,0.025817,-0.048020,0.181970,0.041222,0.035184,0.001312,-0.107346,0.070236,-0.184013,-0.043722,0.237125,-0.106214,-0.005608,0.025885
Sp. Def,0.717609,0.378718,0.263990,0.510747,0.506121,1.000000,0.259133,0.028486,0.363937,NaN,-0.081821,-0.021162,0.139235,0.016502,0.092574,0.014125,0.025719,-0.008817,0.044885,-0.005243,-0.076820,0.060370,-0.112124,-0.046722,0.190286,0.019179,0.103424,-0.024765
Speed,0.575943,0.175952,0.381240,0.015227,0.473018,0.259133,1.000000,-0.023121,0.326715,NaN,-0.071435,0.067976,0.123244,0.130356,-0.098169,0.075673,0.072541,0.237016,-0.060599,-0.095578,-0.095803,-0.005371,0.052224,-0.030134,0.108020,-0.165331,-0.098291,-0.049030
Generation,0.048384,0.058683,0.051451,0.042419,0.036437,0.028486,-0.023121,1.000000,0.079794,NaN,-0.019231,0.093959,0.102059,0.005638,0.065809,0.050980,0.006327,-0.035587,0.155587,0.072716,-0.050801,0.037865,-0.036168,-0.191679,-0.021772,0.009356,0.078924,-0.104981
Legendary,0.501758,0.273620,0.345408,0.246377,0.448907,0.363937,0.326715,0.079794,1.000000,NaN,-0.093522,-0.021419,0.225625,0.017719,-0.005248,-0.005633,0.047219,0.093584,-0.014494,-0.066736,-0.007329,0.041136,-0.086246,-0.086195,0.169224,-0.012571,0.019437,-0.065781
check total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bug,-0.145781,-0.154326,-0.070168,-0.027563,-0.185128,-0.081821,-0.071435,-0.019231,-0.093522,NaN,1.000000,-0.082062,-0.081200,-0.045111,-0.072148,-0.048645,-0.060536,0.064571,-0.058915,-0.034430,-0.063544,-0.070229,-0.120219,0.121210,-0.111968,-0.003706,0.047178,-0.123983
Dark,0.056154,0.009986,0.143057,-0.024293,0.036953,-0.021162,0.067976,0.093959,-0.021419,NaN,-0.082062,1.000000,-0.003963,-0.067375,-0.059864,-0.007791,-0.020368,-0.022164,0.001484,-0.048339,-0.023480,-0.010163,-0.099751,-0.018227,-0.044327,-0.033493,-0.023978,-0.028548
Dragon,0.229705,0.138023,0.212999,0.105864,0.194388,0.139235,0.123244,0.102059,0.225625,NaN,-0.081200,-0.003963,1.000000,-0.024000,-0.035541,-0.068775,-0.038069,0.026237,-0.019410,-0.078818,0.052430,0.015173,-0.098702,-0.055525,-0.026557,-0.032360,-0.044417,-0.083285
Electric,0.020971,-0.061303,-0.075471,-0.060502,0.127434,0.016502,0.130356,0.005638,0.017719,NaN,-0.045111,-0.067375,-0.024000,1.000000,-0.035541,-0.068775,-0.057104,-0.020407,-0.041592,-0.078818,-0.059420,-0.033382,-0.067737,-0.074838,-0.091928,-0.072188,-0.001346,-0.069109
Fairy,-0.036698,-0.007046,-0.123250,-0.025342,0.025817,0.092574,-0.098169,0.065809,-0.005248,NaN,-0.072148,-0.059864,-0.035541,-0.035541,1.000000,-0.061108,-0.067651,-0.052669,-0.056665,-0.048756,-0.069360,-0.051232,-0.001720,-0.066495,0.027227,0.002212,0.013155,-0.067703
Fighting,0.077786,0.055398,0.210706,0.001830,-0.048020,0.014125,0.075673,0.050980,-0.005633,NaN,-0.048645,-0.007791,-0.068775,-0.068775,-0.061108,1.000000,0.051130,-0.086119,-0.065792,-0.051171,-0.080531,-0.059483,-0.071687,-0.039613,0.000596,-0.055090,-0.005161,-0.073778
Fire,0.078726,0.010371,0.046438,-0.035472,0.181970,0.025719,0.072541,0.006327,0.047219,NaN,-0.060536,-0.020368,-0.038069,-0.057104,-0.067651,0.051130,1.000000,-0.028855,-0.013459,-0.108248,-0.022621,-0.065851,-0.085097,-0.085471,-0.061243,-0.064677,-0.056108,-0.114850
Flying,0.059383,0.031394,0.014373,-0.068486,0.041222,-0.008817,0.237016,-0.035587,0.093584,NaN,0.064571,-0.022164,0.026237,-0.020407,-0.052669,-0.086119,-0.028855,1.000000,-0.061555,-0.081366,-0.060578,-0.049498,0.125506,-0.067950,-0.063872,-0.048221,-0.081400,-0.092030
Ghost,0.003641,-0.062262,-0.015735,0.060864,0.035184,0.044885,-0.060599,0.155587,-0.014494,NaN,-0.058915,0.001484,-0.019410,-0.041592,-0.056665,-0.065792,-0.013459,-0.061555,1.000000,0.075316,-0.035908,-0.029914,-0.094420,0.008736,-0.070947,-0.069057,0.026479,-0.077314
Grass,-0.052592,-0.046120,-0.062674,-0.006948,0.001312,-0.005243,-0.095578,0.072716,-0.066736,NaN,-0.034430,-0.048339,-0.078818,-0.078818,-0.048756,-0.051171,-0.108248,-0.081366,0.075316,1.000000,-0.097033,-0.027476,-0.117156,0.110372,-0.094009,-0.072829,-0.061537,-0.126894
Ground,0.015060,0.074916,0.127416,0.134451,-0.107346,-0.076820,-0.095803,-0.050801,-0.007329,NaN,-0.063544,-0.023480,0.052430,-0.059420,-0.069360,-0.080531,-0.022621,-0.060578,-0.035908,-0.097033,1.000000,-0.003872,-0.102044,-0.053878,-0.079079,0.072085,-0.020771,-0.006844
Ice,0.060248,0.082021,0.021007,0.020174,0.070236,0.060370,-0.005371,0.037865,0.041136,NaN,-0.070229,-0.010163,0.015173,-0.033382,-0.051232,-0.059483,-0.065851,-0.049498,-0.029914,-0.027476,-0.003872,1.000000,-0.085366,-0.064726,-0.042311,-0.017110,-0.057042,0.000242
Normal,-0.105331,0.111999,-0.074769,-0.174609,-0.184013,-0.112124,0.052224,-0.036168,-0.086246,NaN,-0.120219,-0.099751,-0.098702,-0.067737,-0.001720,-0.071687,-0.085097,0.125506,-0.094420,-0.117156,-0.102044,-0.085366,1.000000,-0.110800,-0.112381,-0.106877,-0.097645,-0.154994
Poison,-0.090441,-0.075668,-0.073370,-0.093942,-0.043722,-0.046722,-0.030134,-0.191679,-0.086195,NaN,0.121210,-0.018227,-0.055525,-0.074838,-0.066495,-0.039613,-0.085471,-0.067950,0.008736,0.110372,-0.053878,-0.064726,-0.110800,1.000000,-0.103195,-0.081036,-0.074036,-0.073986
Psychic,0.124688,0.027239,-0.069773,0.010685,0.237125,0.190286,0.108020,-0.021772,0.169224,NaN,-0.111968,-0.044327,-0.026557,-0.091928,0.027227,0.000596,-0.061243,-0.063872,-0.070947,-0.094009,-0.079079,-0.042311,-0.112381,-0.103195,1.000000,-0.069031,0.024540,-0.099639
Rock,0.032731,-0.035514,0.101043,0.298242,-0.106214,0.019179,-0.165331,0.009356,-0.012571,NaN,-0.003706,-0.033493,-0.032360,-0.072188,0.002212,-0.055090,-0.064677,-0.048221,-0.069057,-0.072829,0.072085,-0.017110,-0.106877,-0.081036,-0.069031,1.000000,0.049202,0.011447
Steel,0.109703,-0.043037,0.107505,0.350559,-0.005608,0.103424,-0.098291,0.078924,0.019437,NaN,0.047178,-0.023978,-0.044417,-0.001346,0.013155,-0.005161,-0.056108,-0.081400,0.026479,-0.061537,-0.020771,-0.057042,-0.097645,-0.074036,0.024540,0.049202,1.000000,-0.096131
Water,-0.021665,0.029906,-0.070578,0.006259,0.025885,-0.024765,-0.049030,-0.104981,-0.065781,NaN,-0.123983,-0.028548,-0.083285,-0.069109,-0.067703,-0.073778,-0.114850,-0.092030,-0.077314,-0.126894,-0.006844,0.000242,-0.154994,-0.073986,-0.099639,0.011447,-0.096131,1.000000

In [20]:
pokemon_onehot_corr['Total'].sort_values(ascending = False)

Total          1.000000
Sp. Atk        0.747250
Attack         0.736211
Sp. Def        0.717609
HP             0.618748
Defense        0.612787
Speed          0.575943
Legendary      0.501758
Dragon         0.229705
Psychic        0.124688
Steel          0.109703
Fire           0.078726
Fighting       0.077786
Ice            0.060248
Flying         0.059383
Dark           0.056154
Generation     0.048384
Rock           0.032731
Electric       0.020971
Ground         0.015060
Ghost          0.003641
Water         -0.021665
Fairy         -0.036698
Grass         -0.052592
Poison        -0.090441
Normal        -0.105331
Bug           -0.145781
check total         NaN
Name: Total, dtype: float64

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [ ]:
# your code here